### ISSUE TITLE
Read-only site

### ISSUE THREAD

**Issue by Nopfed** [art-by-city/dapp#143]
- [ ] disable interactions involving warp
  - [x] disable curation button/page
  - [x] disable follow button
  - [x] disable upload
  - [x] disable portals

**Comment by Nopfed** [comment]
'Access to fetch has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header present on the requested resource.

Net Error failed 429 too many requests

**Comment by jim-toth** [comment]
> 'Access to fetch has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header present on the requested resource.
> 
> Net Error failed 429 too many requests

prob warp stuff, just try to disable as much warp shit as possible.  might require sdk changes
